### ISSUE TITLE
generated code contains case classes ?

### ISSUE THREAD

**Issue by chandu0101** [apollographql/react-apollo-scalajs#8]
generated code contains `case classes` for output , which means an extra step in parsing ..

why not scala.js js.Object traits  ?

**Comment by shadaj** [comment]
Case classes were chosen because they are a lot easier to handle within Scala code, since they provide functions to perform actions like copying with some values replaced. In addition, the conversion process is very lightweight with most JS types simply casted into their Scala equivalents.

Additionally, js.Object traits prevent us from using natural Scala types like `Option` to handle GraphQL data since all the fields must also be JS types.

**Comment by chandu0101** [comment]
we can generate copy/apply methods on the fly for js.Object traits too.. , anyway i still think case classes is an overkill for this purpose!, rolled my own with scala macro annotations.(no need of invoking SourceGen on every compile..) .
